image: challenges/imageflux
port: 80
domain_suffix: challenge.zeroday.pw
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
securityContext:
  runAsNonRoot: false
  runAsUser: 33
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
