challenge_id: imageflux-7118e514e164759b4ba606000a67697
image: challenges/imageflux

port: 80
domain_suffix: challenges.zeroday.pw
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
securityContext:
  runAsNonRoot: false
  runAsUser: 33
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
